logFilters:
  - code: YN0062
    level: discard
  - code: YN0063
    level: discard
  - code: YN0002
    level: discard
  - code: YN0060
    level: discard
  - code: YN0019
    level: discard

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs
